//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.01.08 at 04:12:40 PM GMT 
//


package com.prem_table_soap.backend.xsdobjects.team;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.prem_table_soap.backend.xsdobjects.team package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.prem_table_soap.backend.xsdobjects.team
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllTeamsRequest }
     * 
     */
    public GetAllTeamsRequest createGetAllTeamsRequest() {
        return new GetAllTeamsRequest();
    }

    /**
     * Create an instance of {@link GetAllTeamsResponse }
     * 
     */
    public GetAllTeamsResponse createGetAllTeamsResponse() {
        return new GetAllTeamsResponse();
    }

    /**
     * Create an instance of {@link TeamDetails }
     * 
     */
    public TeamDetails createTeamDetails() {
        return new TeamDetails();
    }

    /**
     * Create an instance of {@link GetTeamByIdRequest }
     * 
     */
    public GetTeamByIdRequest createGetTeamByIdRequest() {
        return new GetTeamByIdRequest();
    }

    /**
     * Create an instance of {@link GetTeamByIdResponse }
     * 
     */
    public GetTeamByIdResponse createGetTeamByIdResponse() {
        return new GetTeamByIdResponse();
    }

}
