//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.01.08 at 04:12:40 PM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://prem_table_soap.com/backend/xsdObjects/team", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.prem_table_soap.backend.xsdobjects.team;
